### ISSUE TITLE
Unable to read in files (read_hiv_pop() issue?) 

### ISSUE THREAD

**Issue by joshupadhyay** [mrc-ide/specio#10]
Hi, 

I've been trying to use the read_hiv_pop() command, so I tried to run the example code: The pjnz_path points to the right file, but trying to run read_hiv_pop() results in the following error – not sure if this the place to get help but it was the best way I could think of!

(Also, trying to use the _ausrail_ file and read that into read_hiv_pop() gave me the same error.)

Thanks in advance!
<img width="665" alt="Screen Shot 2562-07-29 at 14 34 29" src="https://user-images.githubusercontent.com/47004365/62073092-fff3d680-b20d-11e9-8b3d-d7703a11e2db.png">

**Comment by joshupadhyay** [comment]
I used the **eppasm** package and got what I needed, but I'll still leave this issue open for specio.

**Comment by r-ash** [comment]
Hi,

Thanks for this. It would be good to get this fixed here (we're hoping to replace eppasm's data input and output with this package in the future). I'm struggling to recreate the issue with Botswana2017 data. Can you print a traceback on this error and post it here so I can see exactly where it is coming from?

Also would be super useful if you can enter debugger and print `str(dp_data)` just before the error is thrown.

Thanks.

**Comment by joshupadhyay** [comment]
Here's the traceback.

<img width="928" alt="Screen Shot 2562-08-05 at 21 56 47" src="https://user-images.githubusercontent.com/47004365/62505759-fe0cb300-b7cb-11e9-845a-2d806755c3a2.png">

Perhaps I'm not too familiar with R but the Debug mode is greyed out (couldn't enter the debugger) and I wasn't able to attach an associated breakpoint.

**Comment by r-ash** [comment]
That looks like it is not correctly reading the file from the path

Can you run
```
dp_data <- specio:::get_dp_data(pjnz_path)
str(dp_data)
```
and let me know what the data looks like?

**Comment by joshupadhyay** [comment]
No idea why it doesn't seem to read the data, but if you're not having trouble with the command perhaps it's just a one-off error? 
<img width="446" alt="Screen Shot 2562-08-06 at 12 59 23" src="https://user-images.githubusercontent.com/47004365/62560344-d577ce00-b84a-11e9-843a-46fbdb7a140f.png">

Just wanted to also say thanks for eppasm (and specio) and for trying to help!

**Comment by richfitz** [comment]
Can you please run:

```r
file <- specio:::get_filename_from_extension("DP", pjnz_path)
readLines(unz(pjnz_path, file), n = 3)
```

Can you please also post the result of `sessionInfo()`
