### ISSUE TITLE
No "get_dp_data" function

### ISSUE THREAD

**Issue by skuchukh** [mrc-ide/specio#19]
Good afternoon! 

I  am trying to read into the .DP files from the spectrum projection files however the package "specio" does not seem to include "get_dp_data" even though it has been listed in the vignettes: https://github.com/mrc-ide/specio/blob/0bed6f1a52dff6ff5d8122ecee51900808cbf457/R/read_hivproj_param.R. 

I  was wondering why this might be, and if there are better ways to read in .DP files? 

Kind regards
Salome

**Comment by r-ash** [comment]
Hi, thanks for your issue. 

The function is not exported from this package. The call to `get_dp_data` in the vignette is not rendered knitted vignette. I could make a change to export that function but this repo hasn't seen much maintenance over past few years. I'd suggest using `eppasm::read_dp` https://github.com/mrc-ide/eppasm/blob/47561e6ef41b593d67c26f871729eecc310dc86b/R/read-spectrum-files.R#L31 for this as eppasm has the ability to read from most recent spectrum files and is under more active maintenance than this.

**Comment by skuchukh** [comment]
Thanks so much for your quick response! This helps. 

S
